version: "3.6"
services:
  common:
    build:
      context: ./
      dockerfile: dockerfile
      args:
        work_dir: /tmp/common
    image: common:develop
    container_name: common
    volumes:
      - type: bind
        source: ./
        target: /tmp/common
    tty: true
